import { jsPDF } from 'jspdf';

export const generateItineraryPDF = (data, destination) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  // Helper function to add text with word wrap
  const addText = (text, x, y, maxWidth, fontSize = 12, isBold = false) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, x, y);
    return y + (lines.length * fontSize * 0.5);
  };

  // Helper to check if we need a new page
  const checkNewPage = (requiredSpace) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Header with gradient effect (simulated with rectangles)
  doc.setFillColor(49, 130, 206); // Blue
  doc.rect(0, 0, pageWidth, 50, 'F');
  
  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('WanderAI Travel Itinerary', pageWidth / 2, 25, { align: 'center' });
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(destination || 'Your Destination', pageWidth / 2, 38, { align: 'center' });

  yPosition = 60;
  doc.setTextColor(0, 0, 0);

  // Destination Info
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Trip Overview', margin, yPosition);
  yPosition += 10;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Destination: ${destination || 'Not specified'}`, margin, yPosition);
  yPosition += 8;
  
  if (data.itinerary && data.itinerary.length > 0) {
    doc.text(`Duration: ${data.itinerary.length} days`, margin, yPosition);
    yPosition += 8;
  }

  // Weather Information
  if (data.weather) {
    yPosition += 5;
    doc.setFillColor(240, 248, 255);
    doc.rect(margin, yPosition - 5, pageWidth - 2 * margin, 25, 'F');
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Current Weather', margin + 5, yPosition + 5);
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`${data.weather.city}: ${Math.round(data.weather.temperature)}°C`, margin + 5, yPosition + 13);
    doc.text(`Conditions: ${data.weather.description}`, margin + 5, yPosition + 20);
    
    yPosition += 30;
  }

  // Itinerary Details
  yPosition += 10;
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Day-by-Day Itinerary', margin, yPosition);
  yPosition += 12;

  if (data.itinerary && Array.isArray(data.itinerary)) {
    data.itinerary.forEach((dayPlan, index) => {
      checkNewPage(60);

      // Day Header
      doc.setFillColor(96, 165, 250);
      doc.rect(margin, yPosition - 5, pageWidth - 2 * margin, 12, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text(dayPlan.day || `Day ${index + 1}`, margin + 5, yPosition + 3);
      
      yPosition += 15;
      doc.setTextColor(0, 0, 0);

      // Activities
      if (dayPlan.activities && Array.isArray(dayPlan.activities)) {
        dayPlan.activities.forEach((activity, actIndex) => {
          checkNewPage(20);
          
          doc.setFontSize(11);
          doc.setFont('helvetica', 'normal');
          
          // Bullet point
          doc.setFillColor(49, 130, 206);
          doc.circle(margin + 3, yPosition - 2, 1.5, 'F');
          
          // Activity text with word wrap
          const activityLines = doc.splitTextToSize(activity, pageWidth - 2 * margin - 10);
          doc.text(activityLines, margin + 8, yPosition);
          yPosition += activityLines.length * 6;
        });
      }

      yPosition += 8;
    });
  }

  // Footer
  const footerY = pageHeight - 15;
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by WanderAI - Your AI Travel Companion', pageWidth / 2, footerY, { align: 'center' });
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, footerY + 5, { align: 'center' });

  // Add page numbers
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
  }

  // Save the PDF
  const fileName = `${destination ? destination.replace(/[^a-z0-9]/gi, '_') : 'itinerary'}_${new Date().getTime()}.pdf`;
  doc.save(fileName);
};
